import dotenv from "dotenv"
dotenv.config({
  path: './.env'
})

export const {
  PORT,
  MONGO_URL,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD_NAME,
  GEMINI_API_KEY,
  GEMINI_API_URL
} = process.env

